
## Working with Mapbox GL JS

Mapbox GL JS is a JavaScript library/API
that allows you to make interactive maps that includes shapes, markers, pop-up windows and many other built-in interactive capabilities. But, because it's written in JavaScript and running the browser, anyone with knowledge of JavaScript can extend its capabilities as far as that knowledge can take them. 

What is most important to us is that "data" can be attached to these maps via **geojson format**--making the map, and the rest of the browser an interface for the reader to explore and engage with the output of your research.

For your final projects--the real goal is producing successful, thoughtful, meaningful **output** (that is, dataframes!) that can be explored through the map. More on the specific output you'll need in a moment: first, in basics about JavaScript and Mapbox.

### JavaScript
JavaScript is the programming language that was invented in order to make webpages interactive. JavaScript is an odd and quirky language--it began as a necessity for scripting events on web browsers, and now it has been extended in many directions beyond even the browser. There are many JavaScript tutorials out there -- https://www.w3schools.com/js/ is the most basic, and a decent place to start. With your knowledge of Python you could certainly learn JavaScript via tutorials, books like *Javascript & JQuery, interactive front-end web development*, by Jon Duckett, sites/books like http://eloquentjavascript.net/, and, of course, by patrolling stack overflow.

A few basic things to know:

-All lines in JavaScript are supposed to end with the semi-colon  `;`
Not everyone follows this standard, but that's what you're supposed to do.

-All variables must be initialized/declared using one of the following keywords: `var`, `let`, or `const` (each have a different meaning)

-All functions, loops, if statements etc. are enclosed in brackets `{ }`
For example, here's a JavaScript loop:

`
for (let i=0; i < 10; i++) {
   console.log(i)
}
`

Here is the JavaScript loop through an array (Python list):

`const daysofWeek = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];`

`
for (let i=0; i < daysofWeek.length; i++) {
   console.log(daysofWeek[i])
}
`


**JavaScript console** Notice the `console.log()`, that is the JavaScript version of `print()` The runtime environment for JavaScript is the browser. The console is the JavaScript console that is part of the browser's developer tools. Go to Chrome and select:

`View:Developer:JavaScript Console`

And you can cut-and-paste each of those loops into the console and run it. The console is very helpful for debugging JavaScript. When you have errors on the the page, the console tells you where they are by line number (or tries to), and you can also log variables into the console to make sure everything is working in your script. **If you try to load your map, you should always check the JavaScript console if you have any trouble.**

There's a lot more to know about JavaScript, if you want to learn it. Here a few random things to know:

-Indentations are meaningless in JavaScript (but it's good to use them so your code can be read clearly by a human)

-JavaScript is a messy language, it tries not to be type-specific: so it will automatically convert numerical variables into strings and back--unless it doesn't.

-JavaScript tries not to break--if one part of the script breaks it tries to keep the page going, so sometimes it's hard to debug. 

-JavaScript cares about the DOM -- it reads the page for elements and allows you to change their contents, styles, and lots of other things. For really robust browser-page effects, you should use the Jquery library--it's like short-hand, superpowered JavaScript.

-As I'm sure you all know by now, "lists" in Python are "arrays" in JavaScript, "dictionaries" in Python are "objects" in JavaScript.

-Finally: **you do not need to learn JavaScript to complete this project.** I have built templates that will allow you to build a geojson file that will plug into the mapbox GL page with only a little bit of work and custom changes.


## MAPS ON SCREEN

### SCREEN SPACE
This is the space on the browser, and the screen is measured on an X/Y axis. All of the placement of elements on the screen have a location on these coordinates. The top left-hand corner of the browser is at (x:0,y:0). The further to the right you go the more pixels 'x' is. The further down you go the more pixels 'y' is. To get an idea of locations try this page: 

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_event_mouse_clientxy2

The main thing that a library like Mapbox GL https://docs.mapbox.com/mapbox-gl-js/examples/
does is translate longitudes and latitudes into screen space...

### Templates
There are two templates that I am providing for this project. I have created them so you can go very far with almost no customization at all. There are two main templates available on courseworks:

`map_shapes_template.zip
&
map_points_template.zip`

These both contain two files:

`map.html
geo-data.js`

`map.html` contains all of the HTML, CSS, JavaScript to display the map can make it interactive. How much you want to customize the styles, layout, etc is completely optional. You may not even touch this file.

`geo-data.js` contains the geojson document that you will export from your data frames. 95% of the work is in building this.

### Building the map
In mapbox there is one main function that creates the map: It sets the position, zoom and the tiles. In all likelihood this is the only thing you will need to edit.

```

		var map = new mapboxgl.Map({
			container: 'map',
			style: 'mapbox://styles/mapbox/light-v11',
			center: [0, 0],
			zoom: 11,
			projection: 'naturalEarth'
		});

```

'new mapboxgl.Map({' is where the map first is constructed. 'var map' is the container (variable) that holds the map that you're constructing. The rest of the properties (keys) define different aspects of the map.

### Projections
Over the past year or so Mapbox has implemented different projections. These allow us to move away from Mercator projections which warp the size of countries unacceptably. Both of the templates default to use the 'naturalEarth' projection, which is more accurate. If your map is zoomed in, you might want to consider removing the projection property (above) and return it the map to Mercator, so that the area you're displaying is flatter. For more on projections:
https://docs.mapbox.com/mapbox-gl-js/guides/projections/

### Positioning your map
To make your mapbox project work, you only need to make some small changes on the HTML page (your main goal is generating the proper output for geojson--I'll get to that soon). First here are a few things that you can do to the HTML/Mapbox code.

Center your map and choose your zoom:
`
center: [-21.9270884, 64.1436456], 
zoom: 11
`

Those properties `center` and `zoom` tell the browser what longitude and latitude you want the map to be centered on `[-21.9270884, 64.1436456]`, and the next number is the zoom level `11`. 0 zoom is the whole world, around 12 you start zooming in on a city, after 20 you start getting very very close to the street. `map_points_template` uses the  method .fitBounds() that automatically sets your map's center and zoom--which can be super helpful or make things more complicated--see the template code for details.

There are tons of ways of using and extending Mapbox GL JS. Here are links to examples which might be helpful but probably a rabbit hole, and the actual API documentation which I suggest you don't read until next semester:

https://docs.mapbox.com/mapbox-gl-js/examples/

https://docs.mapbox.com/mapbox-gl-js/api/


## Tiles
What are tiles? Tiles are the background images that are displayed on an interactive screen map. If you have ever gone to [Google Maps](https://www.google.com/maps), you may have noticed that the world according to Google has a particular look and feel to it--very tan, green and blue. This is the default design for Google Maps' tiles. Notice how when you zoom in or move the mouse around, there is an empty gray space before the details of the map show up (if you internet connection is fast you might not see the blank tiles). These are tiles: different illustrations of maps that have been created for various levels of zoom, for every part of the earth. Your browser doesn't download all of them at once--that would be a huge download. Instead, these images of the earth are split up into small tiles and served dynamically to you depending on what you're looking at (what level of zoom, and what geographic location).

One of the advantages and limitations to Mapbox is that it serves tiles--so your maps can work just like Google Maps. The problem of course is that these tiles greatly influence the look and feel of your map. There are and handful of free tiles that Mapbox provides. (And if you are a designer, and have a lot of time on your hands, you can custom-make tiles in Mapbox--do not do this for this project!!!)

Choose your tiles:

`style: 'mapbox://styles/mapbox/light-v11'`

This line lets you access a free tile library from MapBox, are other free tiles include:

https://docs.mapbox.com/api/maps/#styles

### Access token
Like many APIs Mapbox requires that you have access token and register. Please register and get your own access token here:

https://docs.mapbox.com/help/how-mapbox-works/access-tokens/

You will need to make a public token for this project, but please do rather than use the one that's already in the code.

Once you've made your access token replace this line with your code:
```
<script type="text/javascript">
		mapboxgl.accessToken = 'your_code';
```

Those are the super basics--you can go a lot deeper on your own if you want to pursue this project beyond the next week.

### OUTPUT!

Finally, this is really what matters the next week. You are now scraping cleaning and aggregating your data. The question will be, **what do you want people to see?** Here are the main categories you need to focus on in order to get the output you need.  All of these outputs will be constructed in Python, and exported to geojson.

## geojson

The **geojson format** is a standardized form of JSON (JavaScript object notation)--specifically set up to be read by mapping programs (not just Mapbox but all mapping programs). The main thing to understand is that each point or shape on a map is considered a feature. Each feature is held in an array (list) called featuresCollection. Each feature has two important properties (keys)--**geometry**, which contains the longitude and latitude as well as type of shape-- and **properties**, which attaches any additional data to that shape. Here's a simple example of a feature:
`
{
"type": "Feature",
"properties": {"party": "Democrat"},
"geometry": {
"type": "Polygon",
"coordinates": [[
[-109.05, 41.00],
[-102.06, 40.99],
[-102.03, 36.99],
[-109.04, 36.99],
[-109.05, 41.00]
]]
}
`

For your project it is the properties that are 95% of the challenge--but you will need some geometry so that you have interactive shapes on your map.

## Geometry
This is critical to building your GEOJSON object--**geometry** is the property that uses longitude and latitude to plot points or draw shapes on the map. What kind of geometry will you need? There are two aspects of geometry you need to decide on--first what geographical level are you studying (Country, State, City, Address), and second, what kind of shape do you need?

The two templates for this project do imply that you have to make a choice between to main categories of shapes: **polygons** or **points**. Polygons are shapes like the shape of the state or a country. Points are specific locations (like an address) defined by a single set of longitude and latitude. (Usually these different categories of shapes imply different levels of knowledge. You can try to combine them for the project, and the templates may or may not behave...) Most of you will need polygons and multi polygons for Country/State level projects. Some of you will need points (which is simple latitude and longitude). 

Here is a Mapbox example of what shapes are:

https://docs.mapbox.com/mapbox-gl-js/example/geojson-polygon/

But rather than reading a boring tutorial, let's just make some shapes! For a class today we are going to build a very quick point map, and make it work in the points template.

Go to this site, and make some points:

http://geojson.io/

This site allows you to dynamically construct a geojson document. Zoom into whatever you like and start making points. As you might begin to understand as you build your random point map, the real trick with a program like mapbox is that it translates longitude and latitude coordinates to the X and Y grid of the screen space.

Once you have constructed your document's geometry, you can now add the properties from our template:

`{"article": "<p>text</p>", "radius":7, "color": "#FFFF00", "group_id": 1, "group_name": " ", "headline":"", "name": " "}`

While geometry is critical, at this point you only need to know which kind of geometry you'll need--the last step of your project should be locating shapefiles/lng-lats and merging them with your output data that will all be in the "properties" object/dictionary of your final geojson document. (Today's later tutorials begin to take you through those exact steps.)


## Properties 
This is what you should be focusing on building. As you will see, there are only about four or five dictionary keys that you need to build. But you need to build them well.

### Informational properties
**name:** State/Country/City/Court district--the main unit of study/geometry

**headline:** a simple short summary of the information attached to the layer (State/City/Point)--like a headline. This will appear in the pop-up window when you roll over a layer.

**article:** text displayed in the browser, outside of the map--this can be an entire article in HTML. This text will be displayed when you click on a layer.

### Visual grouping properties
**color:** in a hexadecimal ("#660066") or RGB ("rgb(120,0,120)") string -- for more on defining colors, check this out: https://color.adobe.com/create/color-wheel/
Think about how many colors do you need, and what kind of colors would be the most representative, appropriate, effective.

**rating:** This is an alternate to using 'color:' You can specify a numerical range and specify numbers between that range, and the mapbox template will automatically generate a proper color based on the range (Soma made this!). If you want to use this you may need to edit some of the JavaScript here:

`
paint: {
`

And go to Soma's explanation of how this works:

https://gist.github.com/jsoma/c91cfa7a1f4f8346d95ac2a907f0cb0c



**radius**: This only works with points geometry. You can set the radius of each point in pixels.

**group_id:** and **groud_name:** different groupings of data to be displayed separately as multiple layers on the map--this will allow you to display/study multiple aspects of the data.

### geojson row:
Here's an example one row in geojson format that will work with the template:
`
{
      "type": "Feature",
      "properties":{ "name": "My House", "group_name": "best", "group_id": 1, "headline": "home", "article": "<p>What I like about my house is ...,<\/p>", "color": "#660000", "radius": "7" },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -73.96416664123535,
          40.78950978441437
        ]
      }
    }
`

You will have a number of these rows. You want to build them in pandas, and then export them as json document format--See below for how to do this.

## Plugging in your geojson document

But setting this up entails running the server on your computer that you access through your browser. 

So, the much easier way to do this just to take the geojson document, paste the whole thing into the geo-data.js file, directly following the variable:

`infoData = `

So that your first line begins like this:

`infoData = {"type": "FeatureCollection", "features": `

... Continuing on with the entirety of the exported document.


## The process: from shapefiles to dataframes to mapbox

### Shapefiles

Sometimes the biggest challenge is finding the right shapes for your project.

If you simply need country shapes, this is a possible resource:

https://geojson-maps.kyd.au/

If you need to get latitude and longitude's, your best bet is the Google maps API:

https://developers.google.com/maps/documentation/geocoding/start

Some other general US shapes are here:

https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html

If you are doing federal court districts, you are in luck, I found them for you! This is not the easiest search in the world, but eventually I came upon the shape files here:

https://hub.arcgis.com/datasets/fedmaps::u-s-district-courts-2/about

### Mapshaper

This is an online tool for processing, formatting, and exporting shape files. 

http://mapshaper.org/

You drag and drop the shapefile that you downloaded--and, most importantly for the District Court, you want to downsize that so it's not too big. 

Then you export it as geojson...

### pandas > geojson > mapbox

### Prepping for Output

Back to the BBC data that we scraped. 

I am first going to use pandas to get it into a proper format to fit into the mapbox template that I've set up.

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv("backup_BBC2.csv")

In [2]:
df.tail(20)

,movie,director,m_year,critic,crit_org,crit_cn
1750,In the Mood for Love,Wong Kar-wai,2000,Chadi Zeneddine,Doha Film Institute,Qatar
1751,The Tree of Life,Terrence Malick,2011,Chadi Zeneddine,Doha Film Institute,Qatar
1752,A Prophet,Jacques Audiard,2009,Chadi Zeneddine,Doha Film Institute,Qatar
1753,Amélie,Jean-Pierre Jeunet,2001,Chadi Zeneddine,Doha Film Institute,Qatar
1754,Spirited Away,Hayao Miyazaki,2001,Chadi Zeneddine,Doha Film Institute,Qatar
1755,Brokeback Mountain,Ang Lee,2005,Chadi Zeneddine,Doha Film Institute,Qatar
1756,Talk to Her,Pedro Almodóvar,2002,Chadi Zeneddine,Doha Film Institute,Qatar
1757,Mulholland Drive,David Lynch,2001,Chadi Zeneddine,Doha Film Institute,Qatar
1758,Eternal Sunshine of the Spotless Mind,Michel Gondry,2004,Chadi Zeneddine,Doha Film Institute,Qatar
1759,Amour,Michael Haneke,2012,Chadi Zeneddine,Doha Film Institute,Qatar
1760,"Spring, Summer, Fall, Winter…and Spring",Kim Ki-duk,2003,Raymond Zhou,China Daily,China
1761,The Hours,Stephen Daldry,2002,Raymond Zhou,China Daily,China
1762,The Sun Also Rises,Jiang Wen,2007,Raymond Zhou,China Daily,China
1763,A Separation,Asghar Farhadi,2011,Raymond Zhou,China Daily,China
1764,"Lust, Caution",Ang Lee,2007,Raymond Zhou,China Daily,China
1765,The Lives of Others,Florian Henckel von Donnersmarck,2006,Raymond Zhou,China Daily,China
1766,Still Life,Jia Zhangke,2006,Raymond Zhou,China Daily,China
1767,Birdman,Alejandro González Iñárritu,2014,Raymond Zhou,China Daily,China
1768,Infernal Affairs,Andrew Lau and Alan Mak,2002,Raymond Zhou,China Daily,China
1769,City of God,Fernando Meirelles and Kátia Lund,2002,Raymond Zhou,China Daily,China

#### Grouping

Right now, the only useful group is **critics by country**. There's not much else to work with, no other locations. So as far as location mapping goes, that's what we're doing here. 

(If I were to make this a real project, I would add data to this initial data set. And I would most likely find directors by country because that gives me a lot more to work with and map.)

In [3]:
df.groupby('crit_cn')['critic'].nunique()

crit_cn
Argentina        2
Australia        4
Austria          2
Bangladesh       1
Belgium          1
Brazil           1
Canada           5
Chile            2
China            1
Colombia         4
Cuba             5
Egypt            1
France           5
Germany          5
Hong Kong        1
India            5
Indonesia        1
Israel           4
Italy            4
Japan            1
Kazakhstan       1
Lebanon          3
Mexico           2
Namibia          1
Philippines      1
Qatar            1
Senegal          1
Singapore        2
South Africa     1
South Korea      2
Switzerland      1
Taiwan           1
Turkey           2
UAE              3
UK              18
US              82
Name: critic, dtype: int64

In [4]:
#Narrowing down my data into a smaller frame

In [5]:
df1 = df.groupby('crit_cn')['movie'].value_counts().reset_index(name='count')
df1.tail(60)

     crit_cn                                              movie  count
1137      US                                       Take Shelter      1
1138      US                                    Take This Waltz      1
1139      US        Talladega Nights: The Ballad of Ricky Bobby      1
1140      US                                       The Avengers      1
1141      US                                       The Babadook      1
1142      US                                   The Band’s Visit      1
1143      US                               The Bourne Ultimatum      1
1144      US                            The Century of the Self      1
1145      US                      The Colonial Misunderstanding      1
1146      US                                       The Congress      1
1147      US                The Curious Case of Benjamin Button      1
1148      US                                  The Deep Blue Sea      1
1149      US                                    The Descendants      1
1150      US                              The Five Obstructions      1
1151      US                                   The Fourth Watch      1
1152      US                                         The Future      1
1153      US                                    The Gatekeepers      1
1154      US                                   The Ghost Writer      1
1155      US                                  The Hateful Eight      1
1156      US                                           The Host      1
1157      US                                  The King’s Speech      1
1158      US                             The Last of the Unjust      1
1159      US                                The Lives of Others      1
1160      US                                        The Lobster      1
1161      US  The Lord of the Rings: The Fellowship of the Ring      1
1162      US      The Lord of the Rings: The Return of the King      1
1163      US                              The Magdalene Sisters      1
1164      US                                       The Namesake      1
1165      US                                        The Pianist      1
1166      US                                       The Prestige      1
1167      US                  The Romance of Astrea and Celadon      1
1168      US                                      The Sapphires      1
1169      US                                 The Skin I Live In      1
1170      US                            The Squid and the Whale      1
1171      US                      The Story of Marie and Julien      1
1172      US                       The Strange Case of Angelica      1
1173      US                                  The White Meadows      1
1174      US                                   The White Ribbon      1
1175      US                                     The Wind Rises      1
1176      US                                       The Wrestler      1
1177      US                                 This Is Not a Film      1
1178      US                                    This Is the End      1
1179      US                                      Three Monkeys      1
1180      US                                        Three Times      1
1181      US                                           Time Out      1
1182      US                                       Toni Erdmann      1
1183      US                                        Toy Story 3      1
1184      US                                         Two Lovers      1
1185      US                        Warming by the Devil's Fire      1
1186      US                        We Need to Talk About Kevin      1
1187      US                            Wet Hot American Summer      1
1188      US                             What Time Is It There?      1
1189      US      When the Levees Broke: A Requiem in Four Acts      1
1190      US                                Where Do We Go Now?      1
1191      US                                               Wild      1
1192      US                         You Ain’t Seen Nothin’ Yet      1
1193      US                             You Can Count on Me Me      1
1194      US                 You Will Meet a Tall Dark Stranger      1
1195      US                                    You, The Living      1
1196      US                                        Young Adult      1

In [6]:
df1[850:900]

    crit_cn                                  movie  count
850      UK                             Wild Tales      1
851      UK                 Yi Yi: A One and a Two      1
852      UK                        You, The Living      1
853      UK                       Zero Dark Thirty      1
854      US                    There Will Be Blood     21
855      US                       Mulholland Drive     20
856      US  Eternal Sunshine of the Spotless Mind     19
857      US                   In the Mood for Love     18
858      US                    Inside Llewyn Davis     17
859      US                                Boyhood     16
860      US                 Yi Yi: A One and a Two     14
861      US                                 Zodiac     13
862      US                       The Tree of Life     12
863      US                              25th Hour     11
864      US                        Children of Men     11
865      US                 No Country For Old Men     10
866      US                           A Separation      9
867      US                     Mad Max: Fury Road      9
868      US                          Spirited Away      9
869      US             4 Months, 3 Weeks & 2 Days      8
870      US                            Holy Motors      8
871      US                   Synecdoche, New York      8
872      US               The Grand Budapest Hotel      8
873      US                     The Social Network      8
874      US                          A Serious Man      7
875      US                         Certified Copy      7
876      US         Crouching Tiger, Hidden Dragon      7
877      US                   Inglourious Basterds      7
878      US                    Lost in Translation      7
879      US                        Pan's Labyrinth      7
880      US                     The Act of Killing      7
881      US                                 WALL-E      7
882      US                                    Her      6
883      US                             Inside Out      6
884      US                                Memento      6
885      US                        The Dark Knight      6
886      US                             The Master      6
887      US                          The New World      6
888      US                       12 Years a Slave      5
889      US                     Brokeback Mountain      5
890      US                               Brooklyn      5
891      US                          Casino Royale      4
892      US                            City of God      4
893      US                           Femme Fatale      4
894      US                          Inherent Vice      4
895      US                       Moonrise Kingdom      4
896      US                 Only Lovers Left Alive      4
897      US                                  Selma      4
898      US                            Son of Saul      4
899      US                        Stories We Tell      4

The cell above has the output I want,  but I need it to look nice and be combined in a single column.  This is how we build the **"article:"** field of our geojson doc. You need to combine columns of data into readable text.

In [7]:
#Moving the values from the two right columns into a new column
#One that human readers can understand
df1["string"] = df1["movie"] + ": " + df1["count"].astype(str) + np.where(df1["count"]>1, ' votes', ' vote')
df1[850:900]

,crit_cn,movie,count,string
850,UK,Wild Tales,1,Wild Tales: 1 vote
851,UK,Yi Yi: A One and a Two,1,Yi Yi: A One and a Two: 1 vote
852,UK,"You, The Living",1,"You, The Living: 1 vote"
853,UK,Zero Dark Thirty,1,Zero Dark Thirty: 1 vote
854,US,There Will Be Blood,21,There Will Be Blood: 21 votes
855,US,Mulholland Drive,20,Mulholland Drive: 20 votes
856,US,Eternal Sunshine of the Spotless Mind,19,Eternal Sunshine of the Spotless Mind: 19 votes
857,US,In the Mood for Love,18,In the Mood for Love: 18 votes
858,US,Inside Llewyn Davis,17,Inside Llewyn Davis: 17 votes
859,US,Boyhood,16,Boyhood: 16 votes
860,US,Yi Yi: A One and a Two,14,Yi Yi: A One and a Two: 14 votes
861,US,Zodiac,13,Zodiac: 13 votes
862,US,The Tree of Life,12,The Tree of Life: 12 votes
863,US,25th Hour,11,25th Hour: 11 votes
864,US,Children of Men,11,Children of Men: 11 votes
865,US,No Country For Old Men,10,No Country For Old Men: 10 votes
866,US,A Separation,9,A Separation: 9 votes
867,US,Mad Max: Fury Road,9,Mad Max: Fury Road: 9 votes
868,US,Spirited Away,9,Spirited Away: 9 votes
869,US,"4 Months, 3 Weeks & 2 Days",8,"4 Months, 3 Weeks & 2 Days: 8 votes"
870,US,Holy Motors,8,Holy Motors: 8 votes
871,US,"Synecdoche, New York",8,"Synecdoche, New York: 8 votes"
872,US,The Grand Budapest Hotel,8,The Grand Budapest Hotel: 8 votes
873,US,The Social Network,8,The Social Network: 8 votes
874,US,A Serious Man,7,A Serious Man: 7 votes
875,US,Certified Copy,7,Certified Copy: 7 votes
876,US,"Crouching Tiger, Hidden Dragon",7,"Crouching Tiger, Hidden Dragon: 7 votes"
877,US,Inglourious Basterds,7,Inglourious Basterds: 7 votes
878,US,Lost in Translation,7,Lost in Translation: 7 votes
879,US,Pan's Labyrinth,7,Pan's Labyrinth: 7 votes
880,US,The Act of Killing,7,The Act of Killing: 7 votes
881,US,WALL-E,7,WALL-E: 7 votes
882,US,Her,6,Her: 6 votes
883,US,Inside Out,6,Inside Out: 6 votes
884,US,Memento,6,Memento: 6 votes
885,US,The Dark Knight,6,The Dark Knight: 6 votes
886,US,The Master,6,The Master: 6 votes
887,US,The New World,6,The New World: 6 votes
888,US,12 Years a Slave,5,12 Years a Slave: 5 votes
889,US,Brokeback Mountain,5,Brokeback Mountain: 5 votes
890,US,Brooklyn,5,Brooklyn: 5 votes
891,US,Casino Royale,4,Casino Royale: 4 votes
892,US,City of God,4,City of God: 4 votes
893,US,Femme Fatale,4,Femme Fatale: 4 votes
894,US,Inherent Vice,4,Inherent Vice: 4 votes
895,US,Moonrise Kingdom,4,Moonrise Kingdom: 4 votes
896,US,Only Lovers Left Alive,4,Only Lovers Left Alive: 4 votes
897,US,Selma,4,Selma: 4 votes
898,US,Son of Saul,4,Son of Saul: 4 votes
899,US,Stories We Tell,4,Stories We Tell: 4 votes

This is nice but I need to I have only **one row per country**. I do another group, and combine everything together. And when I do that I throw some HTML into there. 

Note this is the opposite of **unwind** (in a way) it is grouping, but it is carrying all of the text in the group into one cell, and formatting it as HTML!

In [8]:
#this is just two different ways to do this:
#one using % as the wild card
#and one using .format and {0} as the wild card

#output = df1.groupby('crit_cn')['string'].apply(lambda x: "<div id='movie'><h1><b>Top Movies</b></h1><P>%s</P></div>" % '</p><p> '.join(x)).reset_index(name='properties.article')
output = df1.groupby('crit_cn')['string'].apply(lambda x: "<div class='movie_list'><h1><b>Top Movies</b></h1><P>{0}</P></div>".format('</p><p> '.join(x))).reset_index(name='properties.article')
output

         crit_cn                                 properties.article
0      Argentina  <div class='movie_list'><h1><b>Top Movies</b><...
1      Australia  <div class='movie_list'><h1><b>Top Movies</b><...
2        Austria  <div class='movie_list'><h1><b>Top Movies</b><...
3     Bangladesh  <div class='movie_list'><h1><b>Top Movies</b><...
4        Belgium  <div class='movie_list'><h1><b>Top Movies</b><...
5         Brazil  <div class='movie_list'><h1><b>Top Movies</b><...
6         Canada  <div class='movie_list'><h1><b>Top Movies</b><...
7          Chile  <div class='movie_list'><h1><b>Top Movies</b><...
8          China  <div class='movie_list'><h1><b>Top Movies</b><...
9       Colombia  <div class='movie_list'><h1><b>Top Movies</b><...
10          Cuba  <div class='movie_list'><h1><b>Top Movies</b><...
11         Egypt  <div class='movie_list'><h1><b>Top Movies</b><...
12        France  <div class='movie_list'><h1><b>Top Movies</b><...
13       Germany  <div class='movie_list'><h1><b>Top Movies</b><...
14     Hong Kong  <div class='movie_list'><h1><b>Top Movies</b><...
15         India  <div class='movie_list'><h1><b>Top Movies</b><...
16     Indonesia  <div class='movie_list'><h1><b>Top Movies</b><...
17        Israel  <div class='movie_list'><h1><b>Top Movies</b><...
18         Italy  <div class='movie_list'><h1><b>Top Movies</b><...
19         Japan  <div class='movie_list'><h1><b>Top Movies</b><...
20    Kazakhstan  <div class='movie_list'><h1><b>Top Movies</b><...
21       Lebanon  <div class='movie_list'><h1><b>Top Movies</b><...
22        Mexico  <div class='movie_list'><h1><b>Top Movies</b><...
23       Namibia  <div class='movie_list'><h1><b>Top Movies</b><...
24   Philippines  <div class='movie_list'><h1><b>Top Movies</b><...
25         Qatar  <div class='movie_list'><h1><b>Top Movies</b><...
26       Senegal  <div class='movie_list'><h1><b>Top Movies</b><...
27     Singapore  <div class='movie_list'><h1><b>Top Movies</b><...
28  South Africa  <div class='movie_list'><h1><b>Top Movies</b><...
29   South Korea  <div class='movie_list'><h1><b>Top Movies</b><...
30   Switzerland  <div class='movie_list'><h1><b>Top Movies</b><...
31        Taiwan  <div class='movie_list'><h1><b>Top Movies</b><...
32        Turkey  <div class='movie_list'><h1><b>Top Movies</b><...
33           UAE  <div class='movie_list'><h1><b>Top Movies</b><...
34            UK  <div class='movie_list'><h1><b>Top Movies</b><...
35            US  <div class='movie_list'><h1><b>Top Movies</b><...

In [9]:
#this is what the UK cell for the article looks like

In [10]:
output.iloc[34]['properties.article']

"<div class='movie_list'><h1><b>Top Movies</b></h1><P>12 Years a Slave: 4 votes</p><p> Boyhood: 4 votes</p><p> Eternal Sunshine of the Spotless Mind: 4 votes</p><p> In the Mood for Love: 4 votes</p><p> Mulholland Drive: 4 votes</p><p> Spirited Away: 4 votes</p><p> The Great Beauty: 4 votes</p><p> The Lives of Others: 4 votes</p><p> There Will Be Blood: 4 votes</p><p> A Separation: 3 votes</p><p> Caché: 3 votes</p><p> Lost in Translation: 3 votes</p><p> Tabu: 3 votes</p><p> Under the Skin: 3 votes</p><p> Birth: 2 votes</p><p> Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan: 2 votes</p><p> Margaret: 2 votes</p><p> Moolaadé: 2 votes</p><p> Red Road: 2 votes</p><p> Synecdoche, New York: 2 votes</p><p> Talk to Her: 2 votes</p><p> The Act of Killing: 2 votes</p><p> The Dark Knight: 2 votes</p><p> The Royal Tenenbaums: 2 votes</p><p> The Tree of Life: 2 votes</p><p> Uncle Boonmee Who Can Recall His Past Lives: 2 votes</p><p> Weekend: 2 votes</p><p> Wendy and Lucy: 2 votes</p><p> White Material: 2 votes</p><p> 35 Shots of Rum: 1 vote</p><p> 4 Months, 3 Weeks & 2 Days: 1 vote</p><p> 5 Broken Cameras: 1 vote</p><p> 7 Letters: 1 vote</p><p> A Letter to Nelson Mandela: 1 vote</p><p> A Single Man: 1 vote</p><p> American Psycho: 1 vote</p><p> Amores Perros: 1 vote</p><p> Amour: 1 vote</p><p> Anomalisa: 1 vote</p><p> Another Year: 1 vote</p><p> Before Sunset: 1 vote</p><p> Blue Is the Warmest Color: 1 vote</p><p> Bridesmaids: 1 vote</p><p> Brokeback Mountain: 1 vote</p><p> Carol: 1 vote</p><p> Children of Men: 1 vote</p><p> City of God: 1 vote</p><p> District 9: 1 vote</p><p> Dogville: 1 vote</p><p> Donnie Darko: 1 vote</p><p> Eden: 1 vote</p><p> Elena: 1 vote</p><p> Everyone Else: 1 vote</p><p> Far From Heaven: 1 vote</p><p> Fat Girl: 1 vote</p><p> Finding Nemo: 1 vote</p><p> Fish Tank: 1 vote</p><p> Four Lions: 1 vote</p><p> Gangs of Wasseypur: 1 vote</p><p> Ghost World: 1 vote</p><p> Good Night and Good Luck: 1 vote</p><p> Goodbye, Dragon Inn: 1 vote</p><p> Gravity: 1 vote</p><p> Hard to Be a God: 1 vote</p><p> Hooligan Sparrow: 1 vote</p><p> I Am Love: 1 vote</p><p> In Vanda’s Room: 1 vote</p><p> Inglourious Basterds: 1 vote</p><p> Inside Llewyn Davis: 1 vote</p><p> Lagaan: Once Upon a Time in India: 1 vote</p><p> Leviathan: 1 vote</p><p> Lourdes: 1 vote</p><p> Mad Max: Fury Road: 1 vote</p><p> Madagascar 3: Europe's Most Wanted: 1 vote</p><p> Master and Commander: The Far Side of the World: 1 vote</p><p> Millennium Mambo: 1 vote</p><p> Monsters, Inc.: 1 vote</p><p> Moon: 1 vote</p><p> Moonrise Kingdom: 1 vote</p><p> Moulin Rouge!: 1 vote</p><p> My Winnipeg: 1 vote</p><p> Nebraska: 1 vote</p><p> Night Will Fall: 1 vote</p><p> No Country For Old Men: 1 vote</p><p> Nostalgia for the Light: 1 vote</p><p> O Brother, Where Art Thou?: 1 vote</p><p> Oldboy: 1 vote</p><p> Once Upon a Time in Anatolia: 1 vote</p><p> Pan's Labyrinth: 1 vote</p><p> Persepolis: 1 vote</p><p> Punch-Drunk Love: 1 vote</p><p> Ratatouille: 1 vote</p><p> Revolutionary Road: 1 vote</p><p> Sembène!: 1 vote</p><p> Shame: 1 vote</p><p> Something Necessary: 1 vote</p><p> Syndromes and a Century: 1 vote</p><p> Team America: World Police: 1 vote</p><p> The Arbor: 1 vote</p><p> The Clock: 1 vote</p><p> The Consequences of Love: 1 vote</p><p> The Diving Bell and the Butterfly: 1 vote</p><p> The Headless Woman: 1 vote</p><p> The Hunt: 1 vote</p><p> The Look of Silence: 1 vote</p><p> The Orphanage: 1 vote</p><p> The Piano Teacher: 1 vote</p><p> The Secret in Their Eyes: 1 vote</p><p> The Social Network: 1 vote</p><p> The Stuart Hall Project: 1 vote</p><p> The Taste of Others: 1 vote</p><p> The Turin Horse: 1 vote</p><p> The White Ribbon: 1 vote</p><p> The Wrestler: 1 vote</p><p> This Is England: 1 vote</p><p> Timbuktu: 1 vote</p><p> Tony Manero: 1 vote</p><p> Toy Story 3: 1 vote</p><p> Tropical Malady: 1 vote</p><p> WALL-E: 1 vote</p><p> Waiting for Happiness: 1 vote</p><p> We Need to Talk About Kevin: 1 vote</p><p> Werckmeister Harmonies: 1 vote</p><p> Whiplash: 1 vote</p><p> Wild Tales: 1 vote</p><p> Yi Yi: A One and a Two: 1 vote</p><p> You, The Living: 1 vote</p><p> Zero Dark Thirty: 1 vote</P></div>"

Now we need our **headline**:  I'm going to have it be the number of critics in the country. I make a mini dataframe That counts the number of critics, and I merge it with my output dataframe.

In [11]:
crits = df.groupby('crit_cn')['critic'].nunique().reset_index(name='properties.critics')
crits

         crit_cn  properties.critics
0      Argentina                   2
1      Australia                   4
2        Austria                   2
3     Bangladesh                   1
4        Belgium                   1
5         Brazil                   1
6         Canada                   5
7          Chile                   2
8          China                   1
9       Colombia                   4
10          Cuba                   5
11         Egypt                   1
12        France                   5
13       Germany                   5
14     Hong Kong                   1
15         India                   5
16     Indonesia                   1
17        Israel                   4
18         Italy                   4
19         Japan                   1
20    Kazakhstan                   1
21       Lebanon                   3
22        Mexico                   2
23       Namibia                   1
24   Philippines                   1
25         Qatar                   1
26       Senegal                   1
27     Singapore                   2
28  South Africa                   1
29   South Korea                   2
30   Switzerland                   1
31        Taiwan                   1
32        Turkey                   2
33           UAE                   3
34            UK                  18
35            US                  82

In [12]:
output = output.merge(crits, how='left', on='crit_cn')

In [13]:
output

,crit_cn,properties.article,properties.critics
0,Argentina,<div class='movie_list'><h1><b>Top Movies</b><...,2
1,Australia,<div class='movie_list'><h1><b>Top Movies</b><...,4
2,Austria,<div class='movie_list'><h1><b>Top Movies</b><...,2
3,Bangladesh,<div class='movie_list'><h1><b>Top Movies</b><...,1
4,Belgium,<div class='movie_list'><h1><b>Top Movies</b><...,1
5,Brazil,<div class='movie_list'><h1><b>Top Movies</b><...,1
6,Canada,<div class='movie_list'><h1><b>Top Movies</b><...,5
7,Chile,<div class='movie_list'><h1><b>Top Movies</b><...,2
8,China,<div class='movie_list'><h1><b>Top Movies</b><...,1
9,Colombia,<div class='movie_list'><h1><b>Top Movies</b><...,4
10,Cuba,<div class='movie_list'><h1><b>Top Movies</b><...,5
11,Egypt,<div class='movie_list'><h1><b>Top Movies</b><...,1
12,France,<div class='movie_list'><h1><b>Top Movies</b><...,5
13,Germany,<div class='movie_list'><h1><b>Top Movies</b><...,5
14,Hong Kong,<div class='movie_list'><h1><b>Top Movies</b><...,1
15,India,<div class='movie_list'><h1><b>Top Movies</b><...,5
16,Indonesia,<div class='movie_list'><h1><b>Top Movies</b><...,1
17,Israel,<div class='movie_list'><h1><b>Top Movies</b><...,4
18,Italy,<div class='movie_list'><h1><b>Top Movies</b><...,4
19,Japan,<div class='movie_list'><h1><b>Top Movies</b><...,1
20,Kazakhstan,<div class='movie_list'><h1><b>Top Movies</b><...,1
21,Lebanon,<div class='movie_list'><h1><b>Top Movies</b><...,3
22,Mexico,<div class='movie_list'><h1><b>Top Movies</b><...,2
23,Namibia,<div class='movie_list'><h1><b>Top Movies</b><...,1
24,Philippines,<div class='movie_list'><h1><b>Top Movies</b><...,1
25,Qatar,<div class='movie_list'><h1><b>Top Movies</b><...,1
26,Senegal,<div class='movie_list'><h1><b>Top Movies</b><...,1
27,Singapore,<div class='movie_list'><h1><b>Top Movies</b><...,2
28,South Africa,<div class='movie_list'><h1><b>Top Movies</b><...,1
29,South Korea,<div class='movie_list'><h1><b>Top Movies</b><...,2
30,Switzerland,<div class='movie_list'><h1><b>Top Movies</b><...,1
31,Taiwan,<div class='movie_list'><h1><b>Top Movies</b><...,1
32,Turkey,<div class='movie_list'><h1><b>Top Movies</b><...,2
33,UAE,<div class='movie_list'><h1><b>Top Movies</b><...,3
34,UK,<div class='movie_list'><h1><b>Top Movies</b><...,18
35,US,<div class='movie_list'><h1><b>Top Movies</b><...,82

In [14]:
#Turn that number and into something readable.
# and I'm keeping the votes as a separate for later
output['properties.headline'] = output['properties.critics'].astype(str) + np.where(output["properties.critics"]>1, ' critics', ' critic')

In [15]:
output

,crit_cn,properties.article,properties.critics,properties.headline
0,Argentina,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics
1,Australia,<div class='movie_list'><h1><b>Top Movies</b><...,4,4 critics
2,Austria,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics
3,Bangladesh,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
4,Belgium,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
5,Brazil,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
6,Canada,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics
7,Chile,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics
8,China,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
9,Colombia,<div class='movie_list'><h1><b>Top Movies</b><...,4,4 critics
10,Cuba,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics
11,Egypt,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
12,France,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics
13,Germany,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics
14,Hong Kong,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
15,India,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics
16,Indonesia,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
17,Israel,<div class='movie_list'><h1><b>Top Movies</b><...,4,4 critics
18,Italy,<div class='movie_list'><h1><b>Top Movies</b><...,4,4 critics
19,Japan,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
20,Kazakhstan,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
21,Lebanon,<div class='movie_list'><h1><b>Top Movies</b><...,3,3 critics
22,Mexico,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics
23,Namibia,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
24,Philippines,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
25,Qatar,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
26,Senegal,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
27,Singapore,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics
28,South Africa,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
29,South Korea,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics
30,Switzerland,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
31,Taiwan,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic
32,Turkey,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics
33,UAE,<div class='movie_list'><h1><b>Top Movies</b><...,3,3 critics
34,UK,<div class='movie_list'><h1><b>Top Movies</b><...,18,18 critics
35,US,<div class='movie_list'><h1><b>Top Movies</b><...,82,82 critics

Now let's **set colors** for our map. (There are ways to do this inside the map, but why not do it in Python just for fun.)

In [16]:
def assign_color(votes):
    if votes < 3:
        return "#00CCE7"
    if votes < 10:
        return "#00AEC5"
    if votes < 20:
        return "#0090A3"
    else:
        return "#007281"

In [17]:

output['properties.color'] = output['properties.critics'].apply(lambda x: assign_color(x))
output

,crit_cn,properties.article,properties.critics,properties.headline,properties.color
0,Argentina,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics,#00CCE7
1,Australia,<div class='movie_list'><h1><b>Top Movies</b><...,4,4 critics,#00AEC5
2,Austria,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics,#00CCE7
3,Bangladesh,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
4,Belgium,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
5,Brazil,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
6,Canada,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics,#00AEC5
7,Chile,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics,#00CCE7
8,China,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
9,Colombia,<div class='movie_list'><h1><b>Top Movies</b><...,4,4 critics,#00AEC5
10,Cuba,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics,#00AEC5
11,Egypt,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
12,France,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics,#00AEC5
13,Germany,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics,#00AEC5
14,Hong Kong,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
15,India,<div class='movie_list'><h1><b>Top Movies</b><...,5,5 critics,#00AEC5
16,Indonesia,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
17,Israel,<div class='movie_list'><h1><b>Top Movies</b><...,4,4 critics,#00AEC5
18,Italy,<div class='movie_list'><h1><b>Top Movies</b><...,4,4 critics,#00AEC5
19,Japan,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
20,Kazakhstan,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
21,Lebanon,<div class='movie_list'><h1><b>Top Movies</b><...,3,3 critics,#00AEC5
22,Mexico,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics,#00CCE7
23,Namibia,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
24,Philippines,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
25,Qatar,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
26,Senegal,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
27,Singapore,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics,#00CCE7
28,South Africa,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
29,South Korea,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics,#00CCE7
30,Switzerland,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
31,Taiwan,<div class='movie_list'><h1><b>Top Movies</b><...,1,1 critic,#00CCE7
32,Turkey,<div class='movie_list'><h1><b>Top Movies</b><...,2,2 critics,#00CCE7
33,UAE,<div class='movie_list'><h1><b>Top Movies</b><...,3,3 critics,#00AEC5
34,UK,<div class='movie_list'><h1><b>Top Movies</b><...,18,18 critics,#0090A3
35,US,<div class='movie_list'><h1><b>Top Movies</b><...,82,82 critics,#007281

Ok, that's some nice output! But we need to join (**merge**) this with a **GeoJson** file.

I will bring the GeoJson file into pandas. But in anticipation, for the fact that there's just no way all the countries are going to match across both files. I'm outputting lists of countries, so I can just do this in Python.

In [18]:
#list of countries in our main df
cn_list = list(output['crit_cn'].unique())
cn_list.sort()
cn_list

['Argentina',
 'Australia',
 'Austria',
 'Bangladesh',
 'Belgium',
 'Brazil',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Cuba',
 'Egypt',
 'France',
 'Germany',
 'Hong Kong',
 'India',
 'Indonesia',
 'Israel',
 'Italy',
 'Japan',
 'Kazakhstan',
 'Lebanon',
 'Mexico',
 'Namibia',
 'Philippines',
 'Qatar',
 'Senegal',
 'Singapore',
 'South Africa',
 'South Korea',
 'Switzerland',
 'Taiwan',
 'Turkey',
 'UAE',
 'UK',
 'US']

**Importing GeoJson**

First, we need to load it as JSON.

Then we normalize it in pandas so we get a flat data frame.

Pay very close attention to the column names. They are maintaining the hierarchy of the JSON data.

In [19]:
import json
from pandas import json_normalize
with open('countries50.geo.json') as json_data:
    geometry_data = json.load(json_data)

FileNotFoundError: [Errno 2] No such file or directory: 'countries50.geo.json'

In [ ]:
geometry_data

In [ ]:
df_geo = pd.DataFrame.from_dict(json_normalize(geometry_data['features']), orient='columns')

In [ ]:
df_geo

In [ ]:
# OK now a list of all the countries in the geo file, this is close to every country.

In [ ]:
geo_list = list(df_geo['properties.sovereignt'].unique())
geo_list.sort()
geo_list

In [ ]:
# get unmatching countries
for cn in cn_list:
    if cn not in geo_list:
        print(cn)

In [ ]:
# look for those in the list
import re
for cn in geo_list:
    if re.match("United", cn, re.IGNORECASE):
        print(cn)
    elif re.match("Hong", cn, re.IGNORECASE):
        print(cn)
#unfortunately hong kong isn't in there

In [ ]:
#rename those unmatching countries in the main dataframe
output['crit_cn'] = output['crit_cn'].str.replace('US','United States of America')
output['crit_cn'] = output['crit_cn'].str.replace('UK','United Kingdom')
output['crit_cn'] = output['crit_cn'].str.replace('UAE','United Arab Emirates')

In [ ]:
output

In [ ]:
#I am not ok with this deleting Hong Kong, so instead, I make an artificial Hong Kong rectangle here:
#https://geojson.io/
#and hand-pasted it into the geojson file
#not perfect...but better than deleting
#importing my new file
import json
from pandas import json_normalize
with open('countries50.geo2.json') as json_data:
    geometry2_data = json.load(json_data)

In [ ]:
df_geo2 = pd.DataFrame.from_dict(json_normalize(geometry2_data['features']), orient='columns')

In [ ]:
#there hong kong in the first row
#all of the properties are wrong, except sovereignt, but that's the only property we need!
df_geo2.head(10)

**Now we can Merge** the two dataframe without have key errors.

Note, this is a **merge left** so it keeps my output, data frame as it was, and just adds three columns from the GeoJson data:

`properties.sovereignt` because that's what I'm joining on

and `geometry.coordinates` and `geometry.type` because those are what the map needs.

In [ ]:
df_final = pd.merge(
    output,df_geo2[["properties.sovereignt","geometry.coordinates","geometry.type"]],
    left_on='crit_cn', 
    right_on = 'properties.sovereignt', how='left')

In [ ]:
df_final

**A custom GeoJson dataframe**

Well, almost. I do want the name of the country to be carried properly into GeoJson format so I change the column name to:

`properties.name`

In [ ]:
df_final = df_final.rename(columns={'crit_cn': 'properties.name'})
df_final

In [ ]:
#turn it back into JSON (list of dictionaries)

In [ ]:
ok_json = json.loads(df_final.to_json(orient='records'))

In [ ]:
#not this is not geojson

In [ ]:
ok_json

In [ ]:
#this function will convert the flat json into the geojson hierarchy

In [ ]:
def process_to_geojson(file):
    geo_data = {"type": "FeatureCollection", "features":[]}
    for row in file:
        this_dict = {"type": "Feature", "properties":{}, "geometry": {}}
        for key, value in row.items():
            key_names = key.split('.')
            if key_names[0] == 'geometry':
                this_dict['geometry'][key_names[1]] = value
            if str(key_names[0]) == 'properties':
                this_dict['properties'][key_names[1]] = value
        geo_data['features'].append(this_dict)
    return geo_data

In [ ]:
geo_format = process_to_geojson(ok_json)

In [ ]:
geo_format

**Done!!!** Saving this as a JavaScript file, because I'm lazy and I don't feel like running a server that loads in a .json file.

In [ ]:
#Variable name
with open('geo-dataAGAIN.js', 'w') as outfile:
    outfile.write("const infoData = ")
#geojson output
with open('geo-data.js', 'a') as outfile:
    json.dump(geo_format, outfile)